name: Upload to testflight

on:
  workflow_call:
  workflow_dispatch:

env:
  ARTIFACT: iphone

jobs:
  uploadToTestFlight:
    name: upload to TestFlight
    runs-on: macos-latest
    steps:
      - name: Download Android 🤖
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: build/android.yml
          workflow_conclusion: success
          branch: main
          name: ${{ ARTIFACT }}
          
      - name: Upload to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: qr_code_generator.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
