name: Build web

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump env context for check
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: |
        echo "$ENV_CONTEXT"
    - name: Dump vars context for check
      env:
        VARS_CONTEXT: ${{ toJson(vars) }}
        TEST_VAR: ${{ vars.WEB_ARTIFACT }}
      run: |
        echo "$TEST_VAR"
        echo "${{ vars.WEB_ARTIFACT }}"
  getVersion:
    name: get version
    runs-on: ubuntu-latest
    if: false
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
           
  buildWeb:
    name: build web 🌐
    runs-on: ubuntu-latest
    needs: getVersion
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Install flutter
        uses: subosito/flutter-action@v2.10.0
      
      - run: flutter doctor -v
      - run: flutter pub get
      
      - name: Build app
        run: flutter build web --build-name ${{ needs.getVersion.outputs.fullSemVer }}.${{ github.run_number }}
        
      - name: Stage artifact file
        run: mv build/web/ ${{ env.ARTIFACT_PATH }}
         
      - name: Upload version file as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ vars.WEB_ARTIFACT }}
          path: ${{ vars.WEB_ARTIFACT_PATH }}
          if-no-files-found: error
