name: Build linux

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
jobs:
  getVersion:
    name: get version
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
          
  buildLinux:
    name: build Linux 🐧
    runs-on: ubuntu-latest
    needs: getVersion
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: "install build dependencies"
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          
      - name: Install flutter
        uses: subosito/flutter-action@v2.10.0
      
      - run: flutter doctor -v
      - run: flutter pub get
      
      - name: Build linux
        run: flutter build linux --build-name ${{ needs.getVersion.outputs.fullSemVer }} --build-number ${{ github.run_number }}

      - name: Creat tarball
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'tar'
          directory: build/linux/x64/release
          path: bundle
          filename: bundle.tar.gz
        
      - name: Stage artifact file
        run: mv build/linux/x64/release/bundle.tar.gz ${{ vars.LINUX_TARBALL_ARTIFACT_PATH }}
      
      - name: Upload version file as artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ vars.LINUX_ARTIFACT }}
          path: ${{ vars.LINUX_TARBALL_ARTIFACT_PATH }}
          if-no-files-found: error
       
