name: Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  github-pages:
    uses: ./.github/workflows/release-github-pages.yml
  github:
    uses: ./.github/workflows/release-github.yml
  google-play:
    uses: ./.github/workflows/release-google-play.yml
  testflight:
    uses: ./.github/workflows/release-testflight.yml
