name: Release on github
on:
  workflow_call:
  workflow_dispatch:

env:
  WEB_ARTIFACT_ZIP: qr_code_generator-web.zip
  
jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Android 🤖
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-android.yml
          workflow_conclusion: success
          branch: main
          name: ${{ vars.ANDROID_ARTIFACT }}
          
      - name: Download iOS 🍏
        uses: dawidd6/action-download-artifact@v6
        if: false
        with:
          workflow: build-ios.yml
          workflow_conclusion: success
          branch: main
          name: ${{ vars.IOS_ARTIFACT }}
          
      - name: Download linux 🐧
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-linux.yml
          workflow_conclusion: success
          branch: main
          name: ${{ vars.LINUX_ARTIFACT }}
          
      - name: Download windows 🪟
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-windows.yml
          workflow_conclusion: success
          branch: main
          name: ${{ vars.WINDOWS_ARTIFACT }}

      - name: Download web 🌐
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-web.yml
          workflow_conclusion: success
          branch: main
          name: ${{ vars.WEB_ARTIFACT }}
          path: web
          
      - name: Zip web
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          path: web
          filename: ${{ env.WEB_ARTIFACT_ZIP }}
          
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ vars.ANDROID_APK_ARTIFACT_PATH }},${{ vars.ANDROID_APP_BUNDLE_ARTIFACT_PATH }},${{ vars.LINUX_TARBALL_ARTIFACT_PATH }},${{ vars.WINDOWS_INSTALLER_ARTIFACT_PATH }},${{ env.WEB_ARTIFACT_ZIP }}"
