name: Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download aab 🤖
        if: ${{ false }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-android.aab
          
      - name: Download apk 🤖
        if: ${{ false }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-android.apk
          
      - name: Download linux 🐧
        if: ${{ false }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-linux.tar.gz
          
      - name: Download windows 🪟
        if: ${{ false }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-windows.msix

      - name: Download web 🌐
        if: ${{ false }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-web.zip
          
      - name: create release
        if: ${{ false }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qr_code_generator-android.apk,qr_code_generator-android.aab,qr_code_generator-linux.tar.gz,qr_code_generator-windows.msix,qr_code_generator-web.msix"
          
  publish-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-web.zip
          
      - name: Unzip artifact
        run: unzip qr_code_generator-web.zip
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: qr_code_generator-web
