name: Release

on:
  push:
#     tags:
#       - 'v*'
      
jobs:
  github-release:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Download aab 🤖
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-android.aab
          
      - name: Download apk 🤖
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-android.apk
          
      - name: Download linux 🐧
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-linux.tar.gz
          
      - name: Download windows 🪟
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-windows.msix

      - name: Download web 🌐
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: qr_code_generator-web.zip
          
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qr_code_generator-android.apk,qr_code_generator-android.aab,qr_code_generator-linux.tar.gz,qr_code_generator-windows.msix,qr_code_generator-web.msix"
          
  publish-to-github-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: app
          
      - name: Unzip artifact
        run: unzip qr_code_generator-web.zip -d qr_code_generator-web
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
