name: Upload to testflight

on:
  workflow_call:
  workflow_dispatch:

jobs:
  uploadToTestFlight:
    name: upload to TestFlight
    runs-on: macos-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ vars.IOS_ARTIFACT }}
          
      - name: Upload to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: qr_code_generator.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
