name: Release to goole play

on:
  workflow_call:
  workflow_dispatch:

jobs:
  promoteRelease:
    name: promote on GooglePlay
    runs-on: ubuntu-latest
    steps:
      - name: Promote Google Play Release Track
        uses: kevin-david/promote-play-release@v1.0.0
        with:
          service-account-json-raw: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
          package-name: com.wimvanlaer.qr_code_generator
