name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3      
      
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2.8.0
      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos
        
